### PR TITLE
Fix build error

### PR DESCRIPTION
**Pull request by nazunamoe**
i have error on compile this kernel
these commits will solve this problem
thanks

### CODE REVIEW

**Comment by bgcngm** [comment]
There's no problem with the kernel while building inside Android build system.

**Comment by nazunamoe** [comment]
i tried to build with many toolchain, but i can't build anything

**Comment by luca020400** [comment]
You shouldn't build in-line, you can specify a custom out directory for the build and it'll work just fine
make -O `pwd`/../out for example

**Comment by nazunamoe** [comment]
hmm.... i don't know why fail.....i just do like
export ARCH=arm64
export SUBARCH=arm64
export CROSS_COMPILE=~/path/of/toolchain
make capricorn_defconfig
make

**Comment by luca020400** [comment]
export ARCH=arm64
export SUBARCH=arm64
export CROSS_COMPILE=~/path/of/toolchain
mkdir ../out
make -C $(pwd) O=$(pwd)/../out capricorn_defconfig
make -C $(pwd) O=$(pwd)/../out

You'll fine all the built files in $(pwd)/../out

**Comment by nazunamoe** [comment]
ok i'll try it

**Comment by nazunamoe** [comment]
ok it works... thanks a lot

**Pull request closed without merging**
